---
rsync:
  haicj:
    src: root@nginx:/var/log/nginx/
    dest: /home/shjanken/nginx-logs/haicj
  esclt:
    src: root@aliyun:/usr/local/openresty/nginx/logs/
    dest: /home/shjanken/nginx-logs/esclt

analysis:
  output:
    haicj: /home/shjanken/nginx-logs/output/haicj/
    esclt: /home/shjanken/nginx-logs/output/esclt/